### ISSUE TITLE
Custom button React component

### ISSUE THREAD

**Issue by sleepinzombie** [vashist02/react-ts-contenful#16]
Create the custom **Button** React component under `src/common` along a Storybook story.

Provide several themed buttons as below:
- Primary
- Secondary
- Tertiary

### Tasks
- [x] Create Button React component
- [x] Add Storybook integration
- [x] Create 3 themed buttons
- [x] Define necessary props that can be used for the component
