### ISSUE TITLE
Custom card React component

### ISSUE THREAD

**Issue by sleepinzombie** [vashist02/react-ts-contenful#17]
Create the custom **Card** React component under `src/common` along a Storybook story.

### Tasks
- [ ] Create Card React component
- [ ] Add Storybook integration
- [ ] Define necessary props that can be used for the component
